service: graphql-training

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  graphql:
    handler: dist/lambda.graphqlHandler
    events:
      - httpApi:
          path: /graphql
          method: post
      - httpApi:
          path: /graphql
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'
