service: graphql-training

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  graphql:
    handler: src/lambda.graphqlHandler
    events:
      - httpApi:
          path: /graphql
          method: post
      - httpApi:
          path: /graphql
          method: get

plugins:
  - serverless-offline
