version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: graphql-training-postgres
    ports:
      - "8765:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql_training
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

volumes:
  postgres-data:
