version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: graphql-training-postgres
    ports:
      - "8765:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql_training
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: graphql-training-jaeger
    ports:
      - 16686:16686   # Jaeger UI
      - 14268:14268   # Jaeger HTTP/JSON Collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: graphql-training-otel-collector
    volumes:
      - ./collector-config.yml:/etc/otelcol/config.yaml
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - 4318:4318     # Only OTLP HTTP

volumes:
  postgres-data:
